server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

rabbitmq:
  service:
    order:
      exchange-response-name: payment-response-exchange
      queue-response-name: payment-response-queue
      queue-request-name: payment-request-queue
