spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8081

resilience4j:
  retry:
    instances:
      PaymentRetry:
        maxAttempts: 3                  # всего 3 попытки (1 исходная + 2 retry)
        waitDuration: 500ms             # базовая задержка
        enableExponentialBackoff: true  # экспоненциальный backoff
        exponentialBackoffMultiplier: 2 # 500ms → 1s → 2s
        retryExceptions:
          - feign.FeignException.InternalServerError  # 500
          - feign.FeignException.ServiceUnavailable    # 503
          - feign.FeignException.GatewayTimeout        # 504
          - java.net.ConnectException
          - java.net.SocketTimeoutException

  circuitbreaker:
    instances:
      PaymentCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        recordExceptions:
          - feign.FeignException.InternalServerError  # 500
          - feign.FeignException.ServiceUnavailable    # 503
          - feign.FeignException.GatewayTimeout        # 504
          - java.net.ConnectException
          - java.net.SocketTimeoutException

  bulkhead:
    instances:
      doctorClientBulkhead:
        maxConcurrentCalls: 5 # Максимальное число параллельных вызовов, разрешенных одновременно
        maxWaitDuration: 0s # Время ожидания, если все слоты заняты; 0 -- отказ сразу, без ожидания

  ratelimiter:
    instances:
      PaymentRateLimiter:
        limit-for-period: 10 # Количество разрешений за период
        limit-refresh-period: # Период обновления лимита
          seconds: 60
        timeout-duration: # Максимальное время ожидания разрешения
          seconds: 1
        registerHealthIndicator: true    # Регистрировать индикатор здоровья для Spring Boot Actuator
        eventConsumerBufferSize: 100     # Размер буфера для событий RateLimiter
